### PR TITLE
Feature/in 7 add shop level

### PR DESCRIPTION
**Pull request by fkrdud1125**
Changes in shop UI, levels. Added Break limit

### CODE REVIEW

**Review by StableSub — CHANGES_REQUESTED** [review]
Please delete the comment.
It seems to be more efficient to process variables by declaring them as arrays.

**Review by StableSub — APPROVED** [review]
LGTM

**Comment by seunghyun-sh** [comment]
LGTM :) 👍

**Review by SKH0501 — APPROVED** [review]
LGTM :)

**Pull request merged**
